name: gbeuzeboc-snapped-cpp-app # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Log the directory it's launched from # 79 char long summary
description: |
  Basic C++ app interacting with the filesystem

grade: stable # must be 'stable' to release into candidate/stable channels
#confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  snapped-cpp-app:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    source: .
    build-packages:
      - libboost-filesystem1.71-dev
    stage-packages:
      - libboost-filesystem1.71.0

apps:
  snapped-cpp-app:
    command: bin/BasicCppSnappedApp
    plugs:
      - home # could be system-files for more access
